config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^', include('learnkg.courses.urls', namespace='courses')),

    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),

    # User management
    url(r'^users/', include('learnkg.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# To enable multilinguality, uncomment the following and comment 'learnkg.middleware.middleware.ForceLangMiddleware',
# urlpatterns += url('^i18n/$', 'django.views.i18n.set_language', name='set_language'),

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]

learnkg/courses/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.TracksListView.as_view(),
        name='tracks_list'
    ),
    url(
        regex=r'^track/(?P<track_id>\d+)$',
        view=views.UnitsListView.as_view(),
        name='units_list'
    ),
    url(
        regex=r'^unit/(?P<unit_id>\d+)$',
        view=views.LessonsListView.as_view(),
        name='lessons_list'
    ),
    url(
        regex=r'^lesson/(?P<lesson_id>\d+)$',
        view=views.ExerciseListView.as_view(),
        name='exercises_list'
    ),
    url(
        regex=r'^exercise/(?P<pk>\d+)/$',
        view=views.ExerciseTemplateView.as_view(),
        name='exercise'
    ),
    url(
        regex=r'^create_submission$',
        view=views.CreateSubmissionView.as_view(),
        name='create_submission'
    ),
]

learnkg/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

learnkg/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

learnkg/courses/views.py
# -*- coding: utf-8 -*-
import json

from django.conf import settings
from django.db.models import Sum
from django.http import JsonResponse
from django.views.generic import CreateView, TemplateView
from django.views.generic.list import ListView

from . models import Track, Unit, Lesson, Exercise, Submission, SubmissionCreationException


class TracksListView(ListView):
    template_name = 'courses/tracks_list.html'
    model = Track

    def get_queryset(self):
        qs = super(TracksListView, self).get_queryset()
        return qs.filter(is_published=True)


class UnitsListView(ListView):
    model = Unit
    template_name = 'courses/units_list.html'

    def get_queryset(self):
        qs = super(UnitsListView, self).get_queryset()
        return qs.filter(track__id=self.kwargs['track_id'], is_published=True)


class LessonsListView(ListView):
    model = Lesson
    template_name = 'courses/lessons_list.html'

    def get_queryset(self):
        qs = super(LessonsListView, self).get_queryset()
        return qs.filter(unit__id=self.kwargs['unit_id'], is_published=True).order_by('id')

    def get_context_data(self, **kwargs):
        context = super(LessonsListView, self).get_context_data(**kwargs)
        context['lessons_duration'] = self.get_queryset().aggregate(
            Sum('lesson_exercise__duration'))['lesson_exercise__duration__sum']
        return context


class ExerciseListView(ListView):
    model = Exercise
    template_name = 'courses/exercise_list.html'

    def get_queryset(self):
        qs = super(ExerciseListView, self).get_queryset()
        return qs.filter(lesson__id=self.kwargs['lesson_id'], is_published=True)

    def get_context_data(self, **kwargs):
        context = super(ExerciseListView, self).get_context_data(**kwargs)
        context['lesson_duration'] = self.get_queryset().aggregate(Sum('duration'))['duration__sum']
        return context


class ExerciseTemplateView(TemplateView):
    template_name = 'courses/exercise.html'

    def get_context_data(self, **kwargs):
        context = super(ExerciseTemplateView, self).get_context_data(**kwargs)
        obj = Exercise.objects.get(id=kwargs['pk'])
        current_object = self._get_current_obj(obj)
        context['object'] = obj
        context['lecture'] = current_object.lecture
        context['instruction'] = current_object.instruction
        context['hint'] = current_object.hint
        context['default_code'] = self._get_default_code(current_object)
        context['unit_test'] = current_object.unit_test
        context['input_should_contain'] = current_object.input_should_contain
        context['input_should_not_contain'] = current_object.input_should_not_contain
        context['input_error_text'] = current_object.input_error_text
        context['output_should_contain'] = current_object.output_should_contain
        context['output_should_not_contain'] = current_object.output_should_not_contain
        context['output_error_text'] = current_object.output_error_text
        context['outputElementId'] = settings.OUTPUT_CONTAINER_ID_IN_EXERCISES_TEMPLATE
        return context

    def _get_current_obj(self, obj):
        try:
            return Submission.objects.get(exercise__id=obj.id, user=self.request.user)
        except Submission.DoesNotExist:
            return obj

    @staticmethod
    def _get_default_code(current_object):
        try:
            return current_object.default_code
        except AttributeError:
            return current_object.submitted_code


class CreateSubmissionView(CreateView):
    model = Submission

    def post(self, request, *args, **kwargs):
        data = request.POST
        user = request.user
        if not user.is_authenticated():
            return JsonResponse({'not_logged_in': True, 'saved': False})
        exercise = self._get_exercise(data)
        submitted_code = data['submitted_code']
        passed = json.loads(data['passed'])
        try:
            self.model.create_from_exercise(user=user, exercise=exercise, submitted_code=submitted_code, passed=passed)
            return JsonResponse({'saved': True})
        except SubmissionCreationException:
            return JsonResponse({'saved': False})

    @staticmethod
    def _get_exercise(data):
        exercise = Exercise.objects.get(pk=json.loads(data['exercise']))
        if exercise:
            return exercise
        return JsonResponse({'saved': False})

learnkg/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

learnkg/templates/courses/exercise_list.html
{% extends "base.html" %}
{% load static %}{% load i18n %}
{% block title %}{% trans 'Exercises' %}{% endblock %}

{% block navbar %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'courses:units_list' object_list.0.lesson.unit.track.id %}">
            {{ object_list.0.lesson.unit.track.name }}
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'courses:lessons_list' object_list.0.lesson.unit.id %}">
            {{ object_list.0.lesson.unit.name }}
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link active" href="{% url 'courses:exercises_list' object_list.0.lesson.id %}">
            {{ object_list.0.lesson.name }}
        </a>
    </li>
{% endblock navbar %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="">
                <h1>{% trans 'Exercises' %}.</h1>

                <div>{% trans 'Duration:' %} {{ lesson_duration }} {% trans 'min.' %}</div>
            </div>

            <div class="list-group">
                {% for exercise in object_list %}
                    <a href="{% url 'courses:exercise' exercise.id %}" class="list-group-item">
                        <h4 class="list-group-item-heading">{{ exercise.name }}</h4>
                        <h6>{% trans 'Exercise duration:' %} {{ exercise.duration }} {% trans 'min.' %}</h6>
                    </a>
                {% endfor %}

            </div>
        </div>
    </div>

{% endblock content %}

learnkg/templates/courses/lessons_list.html
{% extends "base.html" %}
{% load static %}{% load i18n %}
{% block title %}{% trans 'Lessons' %}{% endblock %}


{% block navbar %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'courses:units_list' object_list.0.unit.track.id %}">
            {{ object_list.0.unit.track.name }}
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link active" href="{% url 'courses:lessons_list' object_list.0.unit.id %}">
            {{ object_list.0.unit.name }}
        </a>
    </li>
{% endblock navbar %}

{% block content %}

    <div class="container">
        <div class="row">
            <div>
                {# Translators: the following would look like this -- Unit 1: Python syntax lessons #}
                <h1>{{ object_list.0.unit.name }} {% trans 'lessons' %}</h1>

                <div class="padding-bottom-5px">{% trans 'Overall Duration:' %} {{ lessons_duration }} {% trans 'min.' %}</div>
            </div>
            <div class="list-group">
                {% for lesson in object_list %}
                    <a href="{% url 'courses:exercises_list' lesson.id %}" class="list-group-item">
                        <h4 class="list-group-item-heading">{{ lesson.name }}</h4>
                        <h5 class="list-group-item-heading">{% trans 'Number of exercises:' %} {{ lesson.exercises_number }}</h5>
                        <h5 class="list-group-item-heading">{% trans 'Duration of exercises:' %} {{ lesson.exercises_duration }} {% trans 'min.' %}</h5>
                    </a>
                {% endfor %}

            </div>
        </div>

    </div>

{% endblock content %}

learnkg/templates/courses/tracks_list.html
{% extends "base.html" %}
{% load static %}{% load i18n %}
{% block title %}{% trans 'Tracks' %}{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">

            <h1>{% trans 'Tracks' %}</h1>

            <div class="list-group">
                {% for track in object_list %}
                    <a href="{% url 'courses:units_list' track.id %}" class="list-group-item">
                        <h4 class="list-group-item-heading">{{ track.name }}</h4>
                        <h5 class="list-group-item-heading">{{ track.description }}</h5>
                        <h6 class="list-group-item-heading">{% trans 'Number of units:' %} {{ track.units_count }}</h6>
                        <h6 class="list-group-item-heading">{% trans 'Number of lessons:' %} {{ track.lessons_count }}</h6>
                        <h6 class="list-group-item-heading">{% trans 'Lessons overall duration:' %} {{ track.unit_lessons_duration }}</h6>
                    </a>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock content %}

learnkg/templates/courses/units_list.html
{% extends "base.html" %}
{% load static %}{% load i18n %}
{% block title %}{% trans 'Units' %}{% endblock %}

{% block navbar %}
    <li class="nav-item">
        <a class="nav-link active" href="{% url 'courses:units_list' object_list.0.track.id %}">
            {{ object_list.0.track.name }}
        </a>
    </li>
{% endblock navbar %}

{% block content %}

<div class="container">

    <h1>{% trans 'Units' %}</h1>

    <div class="list-group">
        {% for unit in object_list %}
          <a href="{% url 'courses:lessons_list' unit.id %}" class="list-group-item">
            <h4 class="list-group-item-heading">{{ unit.name }}</h4>
            <h5 class="list-group-item-heading">{{ unit.description }}</h5>
            <h6 class="list-group-item-heading">{% trans 'Number of lessons in unit:' %} {{ unit.lesson_exercises_count }}</h6>
            <h6 class="list-group-item-heading">{% trans 'Overall duration of lessons in unit:' %} {{ unit.lessons_exercises_duration }} {% trans 'min.' %}</h6>
          </a>
        {% endfor %}

    </div>

</div>

{% endblock content %}