config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^', include('learnkg.courses.urls', namespace='courses')),

    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),

    # User management
    url(r'^users/', include('learnkg.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# To enable multilinguality, uncomment the following and comment 'learnkg.middleware.middleware.ForceLangMiddleware',
# urlpatterns += url('^i18n/$', 'django.views.i18n.set_language', name='set_language'),

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]

learnkg/courses/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.TracksListView.as_view(),
        name='tracks_list'
    ),
    url(
        regex=r'^track/(?P<track_id>\d+)$',
        view=views.UnitsListView.as_view(),
        name='units_list'
    ),
    url(
        regex=r'^unit/(?P<unit_id>\d+)$',
        view=views.LessonsListView.as_view(),
        name='lessons_list'
    ),
    url(
        regex=r'^lesson/(?P<lesson_id>\d+)$',
        view=views.ExerciseListView.as_view(),
        name='exercises_list'
    ),
    url(
        regex=r'^exercise/(?P<pk>\d+)/$',
        view=views.ExerciseTemplateView.as_view(),
        name='exercise'
    ),
    url(
        regex=r'^create_submission$',
        view=views.CreateSubmissionView.as_view(),
        name='create_submission'
    ),
]

learnkg/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

learnkg/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

learnkg/courses/views.py
# -*- coding: utf-8 -*-
import json

from django.conf import settings
from django.db.models import Sum
from django.http import JsonResponse
from django.views.generic import CreateView, TemplateView
from django.views.generic.list import ListView

from . models import Track, Unit, Lesson, Exercise, Submission, SubmissionCreationException


class TracksListView(ListView):
    template_name = 'courses/tracks_list.html'
    model = Track

    def get_queryset(self):
        qs = super(TracksListView, self).get_queryset()
        return qs.filter(is_published=True)


class UnitsListView(ListView):
    model = Unit
    template_name = 'courses/units_list.html'

    def get_queryset(self):
        qs = super(UnitsListView, self).get_queryset()
        return qs.filter(track__id=self.kwargs['track_id'], is_published=True)


class LessonsListView(ListView):
    model = Lesson
    template_name = 'courses/lessons_list.html'

    def get_queryset(self):
        qs = super(LessonsListView, self).get_queryset()
        return qs.filter(unit__id=self.kwargs['unit_id'], is_published=True).order_by('id')

    def get_context_data(self, **kwargs):
        context = super(LessonsListView, self).get_context_data(**kwargs)
        context['lessons_duration'] = self.get_queryset().aggregate(
            Sum('lesson_exercise__duration'))['lesson_exercise__duration__sum']
        return context


class ExerciseListView(ListView):
    model = Exercise
    template_name = 'courses/exercise_list.html'

    def get_queryset(self):
        qs = super(ExerciseListView, self).get_queryset()
        return qs.filter(lesson__id=self.kwargs['lesson_id'], is_published=True)

    def get_context_data(self, **kwargs):
        context = super(ExerciseListView, self).get_context_data(**kwargs)
        context['lesson_duration'] = self.get_queryset().aggregate(Sum('duration'))['duration__sum']
        return context


class ExerciseTemplateView(TemplateView):
    template_name = 'courses/exercise.html'

    def get_context_data(self, **kwargs):
        context = super(ExerciseTemplateView, self).get_context_data(**kwargs)
        obj = Exercise.objects.get(id=kwargs['pk'])
        current_object = self._get_current_obj(obj)
        context['object'] = obj
        context['lecture'] = current_object.lecture
        context['instruction'] = current_object.instruction
        context['hint'] = current_object.hint
        context['default_code'] = self._get_default_code(current_object)
        context['unit_test'] = current_object.unit_test
        context['input_should_contain'] = current_object.input_should_contain
        context['input_should_not_contain'] = current_object.input_should_not_contain
        context['input_error_text'] = current_object.input_error_text
        context['output_should_contain'] = current_object.output_should_contain
        context['output_should_not_contain'] = current_object.output_should_not_contain
        context['output_error_text'] = current_object.output_error_text
        context['outputElementId'] = settings.OUTPUT_CONTAINER_ID_IN_EXERCISES_TEMPLATE
        return context

    def _get_current_obj(self, obj):
        try:
            return Submission.objects.get(exercise__id=obj.id, user=self.request.user)
        except Submission.DoesNotExist:
            return obj

    @staticmethod
    def _get_default_code(current_object):
        try:
            return current_object.default_code
        except AttributeError:
            return current_object.submitted_code


class CreateSubmissionView(CreateView):
    model = Submission

    def post(self, request, *args, **kwargs):
        data = request.POST
        user = request.user
        if not user.is_authenticated():
            return JsonResponse({'not_logged_in': True, 'saved': False})
        exercise = self._get_exercise(data)
        submitted_code = data['submitted_code']
        passed = json.loads(data['passed'])
        try:
            self.model.create_from_exercise(user=user, exercise=exercise, submitted_code=submitted_code, passed=passed)
            return JsonResponse({'saved': True})
        except SubmissionCreationException:
            return JsonResponse({'saved': False})

    @staticmethod
    def _get_exercise(data):
        exercise = Exercise.objects.get(pk=json.loads(data['exercise']))
        if exercise:
            return exercise
        return JsonResponse({'saved': False})

learnkg/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

learnkg/templates/base.html
{% load static staticfiles i18n %}
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block head_javascript %}
    {% endblock head_javascript %}
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Learn.kg{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="learn python interactive online free интерактивный курс онлайн бесплатный курс по программированию">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="x-icon" />

    {% block css %}
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/css/bootstrap.min.css" integrity="sha384-y3tfxAZXuh4HwSYylfB+J125MxIs6mR5FOHamPBG064zB+AFeWH94NdvaCBm8qnd" crossorigin="anonymous">

    <!-- Your stuff: Third-party css libraries go here -->

    <!-- This file store project specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">

    {% endblock %}
    {% block additional_css %}
    {% endblock %}


  </head>

  <body>

    <div class="m-b">
      <nav class="navbar navbar-dark navbar-static-top bg-inverse">
        <div class="container">
          <a class="navbar-brand" href="/">Learn.kg</a>
          <button type="button" class="navbar-toggler hidden-sm-up pull-xs-right" data-toggle="collapse" data-target="#bs-navbar-collapse-1">
            &#9776;
          </button>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-toggleable-xs" id="bs-navbar-collapse-1">
            <ul class="nav navbar-nav">
                {% block navbar %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'courses:tracks_list' %}">{% trans 'Home' %}</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'about' %}">{% trans 'About' %}</a>
                  </li>
                {% endblock navbar %}
            </ul>

            <ul class="nav navbar-nav pull-xs-right">
              {% if request.user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign out" %}</a>
                </li>
              {% else %}
                <li class="nav-item">
                  <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
                </li>
                <li class="nav-item">
                  <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      <!-- Latest JQuery -->
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>

      <!-- Tether - a requirement for Bootstrap tooltips -->
      <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js"></script>

      <!-- Latest compiled and minified JavaScript -->
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/js/bootstrap.min.js" integrity="sha384-vZ2WRJMwsjRMW/8U7i6PWi6AlO1L79snBrmgiDpgIWJ82z8eA5lenwvxbMV1PAh7" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->

      <!-- place project specific Javascript in this file -->

      <script src="{% static 'js/project.js' %}"></script>

    {% endblock javascript %}
  </body>
</html>